### ISSUE TITLE
Zaak/Activiteit relatie niet aanwezig waar verwacht

### ISSUE THREAD

**Issue by bartromgens** [TweedeKamerDerStaten-Generaal/OpenDataAPI2.0#10]
Voor enkele queries van `Zaak` met een `Activiteit` met een gegeven `Zaak/Kamerstukdossier/Nummer` filter krijg ik geen resultaten.

Mogelijk komt dit doordat `Vergadering` nog niet in de acceptatie omgeving zit. Of omdat deze relatie niet op deze manier aanwezig is (=query/filter is fout). Dit is voor mij niet duidelijk.

Ik heb hier niet direct last van, en heeft geen hoge pioriteit. Als er een makklijk antwoord op is, hoor ik het wel graag.

**Voorbeelden**

Wel activiteiten:
- Query voor zaken met `Activiteit` en `Kamerstukdossier` 31239:
https://gegevensmagazijn-a.tweedekamer.nl/OData/v4/1.0/Zaak?$filter=Activiteit/any(a:a+ne+null)+and+Kamerstukdossier/any(d:+d/Nummer+eq+31239)+and+Verwijderd+eq+false&$format=application/json;odata.metadata=full
Geeft 8 resultaten.

Geen activiteiten:
- Query voor zaken met `Activiteit` en `Kamerstukdossier` 34986:
https://gegevensmagazijn-a.tweedekamer.nl/OData/v4/1.0/Zaak?$filter=Activiteit/any(a:a+ne+null)+and+Kamerstukdossier/any(d:+d/Nummer+eq+34986)+and+Verwijderd+eq+false&$format=application/json;odata.metadata=full
Geeft 0 resultaten.
- Dit dossier heeft op tweedekamer.nl wel activiteiten: https://www.tweedekamer.nl/kamerstukken/wetsvoorstellen/detail?cfg=wetsvoorsteldetails&qry=wetsvoorstel%3A34986

**Comment by DanielVanHilten** [comment]
Er zijn meerdere wegen van Zaak naar Activiteit. De route die jij nu bewandeld is Activiteit rechtstreeks naar Zaak, dan krijg je de gerelateerde Activiteiten. Zie ook het Informatiemodel. Maar jij wilt de Activiteiten waarin de Zaak is behandeld. Dan dien je via Agendapunt te gaan naar Activiteit. Jouw voorbeeld query heb ik hierop aangepast, dan zie ik meerdere Activiteiten terugkomen in het resultaat die overeenkomen met de website. Ik hoor graag van je of dit het antwoord is op je vraag.
`Kamerstukdossier` 34986:
https://gegevensmagazijn-a.tweedekamer.nl/OData/v4/1.0/Zaak?$filter=Agendapunt/any(a:a+ne+null)+and+Kamerstukdossier/any(d:+d/Nummer+eq+34986)+and+Verwijderd+eq+false&$format=application/json;odata.metadata=full&$expand=Agendapunt($expand=Activiteit)

**Comment by bartromgens** [comment]
Ah, ja! Het staat inderdaad gewoon in het datamodel. Dankje.
