### ISSUE TITLE
Besluit: VoorstelTekst is altijd leeg

### ISSUE THREAD

**Issue by DanielVanHilten** [TweedeKamerDerStaten-Generaal/OpenDataAPI2.0#13]
Bij Besluit: VoorstelTekst komt nooit voor omdat het bronsysteem dit niet aanlevert. Deze kolom kan weg.

Technisch: https://gegevensmagazijn-a.tweedekamer.nl/Odata/V4/1.0/Besluit?$filter=VoorstelTekst%20ne%20null

**Comment by Leendertdb** [comment]
Wijzigingen doorgevoerd, komt mee met de volgende acceptatie release.
