### ISSUE TITLE
Personen: Fout in actieve Kamerleden

### ISSUE THREAD

**Issue by JPBenard** [TweedeKamerDerStaten-Generaal/OpenDataAPI2.0#14]
Als ik zoek op actieve Kamerleden krijg ik er wel netjes 150 (het juiste aantal zetels) maar er zitten nog Personen tussen die nu geen Kamerlid meer zijn, zoals Akerboom en Teunissen..

https://gegevensmagazijn-a.tweedekamer.nl/odata/v4/1.0/Persoon?&$filter=Functie%20eq%20%27Tweede%20Kamerlid%27&$select=Achternaam&$orderby=Achternaam%20asc&$count=true
geeft wel 150 Kamerleden maar niet de huidige: bijv. Akerboom (tijdelijke vervanger van Kooten-Arissen) en Teunissen (tijdelijke vervanger van Thieme) zijn weer Oud Kamerlid 

Huidige productieomgeving geeft wel de juiste selectie:
https://gegevensmagazijn.tweedekamer.nl/odata/v3/1.0/Persoon?&$select=Achternaam&$filter=Functie/any(aa:aa/Waarde%20eq%20%27Tweede%20Kamerlid%27)&$format=json&$inlinecount=allpages&$expand=Functie&$orderby=Achternaam%20asc
geeft wel de huidige 150 leden, Thieme en Kooten-Arissen zijn weer terug

**Comment by DanielVanHilten** [comment]
Dit komt omdat de acceptatie omgeving voor deze data (Informatie over Tweede Kamerleden, fracties, commissies, geschenken, reizen, CV's en nevenfuncties) synchroniseert met het bronsysteem op acceptatie die achterloopt qua wijzigingen. In productie zal het bronsysteem op productie gekoppeld zijn die altijd de laatste gegevens bevat. Je kijkt dus naar een iets oudere snapshot van deze entiteiten, toen deze is ingeladen waren de 2 Kamerleden dus nog actief. Dat het recentere aanpassingen zijn is te zien aan het veld TotEnMet:

- https://gegevensmagazijn.tweedekamer.nl/odata/v3/1.0/Persoon?&$select=Achternaam,Fractielid&$filter=Achternaam%20eq%20%27Akerboom%27&$format=json&$inlinecount=allpages&$expand=Fractielid&$orderby=Achternaam%20asc
- https://gegevensmagazijn.tweedekamer.nl/odata/v3/1.0/Persoon?&$select=Achternaam,Fractielid&$filter=Achternaam%20eq%20%27Teunissen%27&$format=json&$inlinecount=allpages&$expand=Fractielid&$orderby=Achternaam%20asc

Met toekomstige acceptatie releases kunnen we tevens het bronsysteem weer laten terugzetten van productie naar acceptatie zodat we de laatste stand hebben.

Voor Verslag en Vergadering is dit tevens het geval. De overige entiteiten worden wel gesynchroniseerd met productie. Hiervoor is gekozen omdat daar nu op productie de meeste problemen mee zijn.

**Comment by JPBenard** [comment]
Goed om te weten. Dankjewel voor de uitleg!

**Comment by DanielVanHilten** [comment]
Het is wat onduidelijk, bedankt voor de melding! Ik heb de ReadMe net aangepast en dit toegevoegd. 
https://github.com/TweedeKamerDerStaten-Generaal/OpenDataAPI2.0
