### ISSUE TITLE
Document: Sommige documenten kun je niet openen

### ISSUE THREAD

**Issue by DanielVanHilten** [TweedeKamerDerStaten-Generaal/OpenDataAPI2.0#15]
Af en toe komt de ContentType van Document niet overeen met de binary zelf. Dit betekent bijvoorbeeld dat de metadata in Document zegt dat het een pdf is maar er wel een Word document (meestal een oudere versie) wordt aangeboden. Hierdoor treedt er een fout op wanneer je het document wilt openen.

**Comment by Leendertdb** [comment]
Dit probleem werd veroorzaakt door een timingsissue tussen het bronsysteem en het Gegevensmagazijn. Er komt een fix mee met de volgende release naar acceptatie waarbij dit probleem wordt opgelost.
