### ISSUE TITLE
PersoonNevenfunctieInkomsten in OData: Bedrag is te hoog

### ISSUE THREAD

**Issue by DanielVanHilten** [TweedeKamerDerStaten-Generaal/OpenDataAPI2.0#20]
Door een conversie fout is het veld Bedrag te hoog. (x 100)

**Voorbeeld:**
_In SyncFeed:_
`<bedrag>80000.00</bedrag>`
_In OData:_
` "Bedrag": 8000000.00,`

**Comment by Leendertdb** [comment]
De conversie fout is opgelost, deze testcase is ook toegevoegd aan de interne unittests. De bugfix komt mee met de volgende acceptatie release.

**Comment by DanielVanHilten** [comment]
Inmiddels is de fix released naar acceptatie.
