### ISSUE TITLE
Verzoek: SyncFeed endpoint met testdata

### ISSUE THREAD

**Issue by joepio** [TweedeKamerDerStaten-Generaal/OpenDataAPI2.0#26]
Aangezien we voor een koppeling met [open raadsinformatie](https://github.com/openstate/open-raadsinformatie) graag gebruik zouden willen maken van de Tweede Kamer Open Data, zou het handig zijn om in de nabije toekomst toegang te hebben tot een SyncFeed endpoint met daarin een dataset die van alle relevante modellen een realistische instantie heeft. Op deze manier kunnen we een implementatie van een SyncFeed extractor in een vroeg stadium testen.

**Comment by DanielVanHilten** [comment]
Beste Joep, hier hebben we onze acceptatie omgeving voor ingericht, of bedoel jij iets anders? Zie ook:
https://gegevensmagazijn-a.tweedekamer.nl/SyncFeed/2.0/Feed
Op acceptatie zijn alle entiteiten gevuld met representatieve data.

**Comment by joepio** [comment]
Dankjewel, Daniel! Dit is inderdaad wat ik zocht.
