### ISSUE TITLE
Zaak: Kabinetsappreciatie toevoeging

### ISSUE THREAD

**Issue by DanielVanHilten** [TweedeKamerDerStaten-Generaal/OpenDataAPI2.0#29]
Bij moties en amendementen worden tegenwoordig de kabinetsappreciaties toegevoegd. Dit veld gaan we tevens aanbieden in de entiteit Zaak: "Kabinetsappreciatie. Mogelijke waarden:

- Geen (expliciete) appreciatie
- Niet beschikbaar bij gewijzigde moties en/of amendementen
- Niet beschikbaar bij moties en/of amendementen vóór 1 april 2019
- Nog niet bekend
- Nog te ontvangen
- Ontraden
- Ontraden, tenzij gewijzigd
- Oordeel Kamer
- Overgenomen
- Verzocht motie aan te houden

**Comment by DanielVanHilten** [comment]
Dit nieuwe veld is inmiddels op acceptatie uitgerold.

**Comment by bartromgens** [comment]
Mooie toevoeging :+1: 

Werkt ook prima! Voorbeeld:

| type | onderwerp | Kabinetsappreciatie |
| -- | -- | -- |
| Motie | Motie van het lid Graus over het voorkomen van overnames van bedrijven van nationaal belang | Ontraden |
| Motie | Motie van het lid Van den Berg over een advies van de WRR over activistisch aandeelhouderschap | Ontraden |
| Motie | Gewijzigde motie van het lid Rudmer Heerema c.s. over bekostiging van onderwijs aan kinderen met een ernstige meervoudige beperking (t.v.v. 31497-297) | Niet beschikbaar bij gewijzigde moties en/of amendementen |
| Motie | Motie van het lid Van der Lee over ruimte voor bewoners in de uitvoeringsfase van de versterkingsoperatie | Oordeel Kamer |
| Motie | Motie van het lid Beertema over een aangifteplicht bij strafbare incidenten | Geen (expliciete) appreciatie |
| Motie | Motie van het lid Dik-Faber c.s. over het inbedden van het programma Eigen Initiatief in de versterkingsaanpak | Oordeel Kamer |
| Motie | Motie van het lid Dik-Faber c.s. over een laagdrempelige toegang tot psychische zorg | Oordeel Kamer |
| Motie | Motie van het lid Kwint over zelfstandige waarheidsvinding door de onderwijsinspectie | Geen (expliciete) appreciatie |
| Motie | Motie van het lid Kwint over meer kennisuitwisseling tussen schoolbesturen en de onderwijsinspectie | Geen (expliciete) appreciatie |
| Motie | Motie van het lid Beckerman c.s. over een forse toename van het aantal inspecties en opnames | Ontraden |

**Comment by DanielVanHilten** [comment]
Inmiddels op productie!
