### ISSUE TITLE
Vraag: hoe bepaal ik of een OData entiteit relatie bestaat?

### ISSUE THREAD

**Issue by bartromgens** [TweedeKamerDerStaten-Generaal/OpenDataAPI2.0#33]
**endpoint**: https://gegevensmagazijn.tweedekamer.nl/OData/v4/2.0

OData is redelijk nieuw voor mij. Waarschijnlijk is dit een algemene OData vraag. Ik kan het antwoord alleen niet vinden in OData documentatie en andere bronnen.

Ik zie dat er soms een `<Related_Entity>_Id` attribute aanwezig is, maar vaak ook niet.

-------------
**Voorbeeld**
https://gegevensmagazijn.tweedekamer.nl/OData/v4/2.0/Besluit(d51ab0ad-fbe7-4f62-91c9-82df53ae7a87)?$format=application/json;odata.metadata=full

Dit Besluit bevat een `Agendapunt_Id`. Hieraan kan ik zien of de relatie bestaat.

Maar een Zaak:
https://gegevensmagazijn.tweedekamer.nl/OData/v4/2.0/Zaak(cc03fd3a-9720-415d-bd8f-7239265ec1a6)?$format=application/json;odata.metadata=full

Bevat geen `Kamerstukdossier_Id`.

---------------

Mogelijk heeft dit te maken met de 'richting' van de relatie in het data model?

Als dit `<Related_Entity>_Id` attribute niet aanwezig is, kan ik de associatie link volgen om te kijken of die bestaat. Ik krijg een 404 response als deze niet bestaat. Dit is opzich prima.

Ik vraag me alleen af of het volgen van de link en controleren op een 404 de enige/beste manier is om te zien of de relatie bestaat.

Samengevat:
- Wanneer kan ik een `<Related_Entity>_Id` verwachten?
- Wat is de aangeraden manier om te bepalen of een relatie bestaat?

Je kan deze vraag negeren en sluiten als dit een algemene OData vraag is die jullie niet makkelijk kunnen beantwoorden.

**Comment by DanielVanHilten** [comment]
**Wanneer kan ik een <Related_Entity>_Id verwachten?**
In het oude OData punt (v3) hadden we deze rechtstreekse relaties niet en moest je alle relaties via een "expand" doen. Verplichte relaties (besluit valt altijd in een agendapunt, een agendapunt valt altijd in een activiteit) zul je dit Id zien. Optionele relaties (Activiteit naar Zaak, Zaak naar Kamerstuk) kun je alleen zien door gebruik te maken van de expand functie. Heb je overigens de SyncFeed API weleens bekeken? Hierin krijg je xml waar meteen alle relaties instaan. Heel handig om je lokale database synchroon te houden.

**Wat is de aangeraden manier om te bepalen of een relatie bestaat?**
Je zult per entiteit de mogelijke expands op moeten vragen en deze tevens verwerken. Er zijn vele expands mogelijk en daarnaast werken ze 2 kanten op. De SyncFeed is misschien een overweging om te gaan gebruiken. Voorbeeld xml:

```
<zaak xmlns:tk="http://www.tweedekamer.nl/xsd/tkData/v1-0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://www.tweedekamer.nl/xsd/tkData/v1-0" id="0927b03e-8caf-46d2-89d0-e485f5cc2c59" tk:bijgewerkt="2019-07-05T12:27:45.0970000" tk:verwijderd="false">
  <nummer>2019Z14652</nummer>
  <soort>Motie</soort>
  <onderwerp>Motie van het lid Agema over tegenstellingen tussen waarnemers en praktijkhouders</onderwerp>
  <gestartOp>2019-07-04T00:00:00</gestartOp>
  <organisatie>Tweede Kamer</organisatie>
  <titel>Eerstelijnszorg</titel>
  <citeertitel xsi:nil="true" />
  <alias xsi:nil="true" />
  <grondslagvoorhang xsi:nil="true" />
  <termijn xsi:nil="true" />
  <vergaderjaar>2018-2019</vergaderjaar>
  <volgnummer>73</volgnummer>
  <status>Vrijgegeven</status>
  <huidigeBehandelstatus xsi:nil="true" />
  <afgedaan>true</afgedaan>
  <grootProject>false</grootProject>
  <kabinetsappreciatie>Ontraden</kabinetsappreciatie>
  <kamerstukdossier ref="356504ae-0a8e-4785-aafa-7174db1e2930" />
  <agendapunt ref="09f0ecf1-df9d-4583-9cdf-6e82465030fb" />
  <agendapunt ref="dedb6c99-f29e-442a-92c2-93b5a542ddfe" />
</zaak>
```
Hier zie je dus meteen alle "refs" waarbij je bij het OData punt dit pas zult zien als je de expand doet.

Kun je hiermee verder?

**Comment by bartromgens** [comment]
Dankjewel voor het antwoord. Duidelijk. Goed te weten hoe dit werkt en bevestiging dat ik niet iets over het hoofd zie of iets raar doe.

Voor de https://github.com/openkamer/tkapi Python bindings (die zorgen dat een 'simpele' gebruiker geen OData kennis nodig heeft), wil ik graag een generieke basis neerzetten die in eerste instatie gewoon werkt. Daarin zie ik bijv. expands als een optimalisatie voor later. De SyncFeed is daar ook niet voor van toepassing (op dit moment), maar goed om te weten.
