### ISSUE TITLE
Parlis HTML links in noot (van Activiteit)

### ISSUE THREAD

**Issue by bwbroersma** [TweedeKamerDerStaten-Generaal/OpenDataAPI2.0#38]
Zie bijv [deze](https://gegevensmagazijn.tweedekamer.nl/SyncFeed/2.0/Entiteiten/b7076363-16fb-4c22-a133-d6416e20cc3f) of [deze](https://gegevensmagazijn.tweedekamer.nl/SyncFeed/2.0/Entiteiten/2a9fc148-5ee9-4053-83b8-b7012ffbf2ce) waar in de `<noot>` de HTML:
```html
Toegevoegd tijdens de <a href="http://parlisweb/parlis/activiteit.aspx?id=...">Regeling van werkzaamheden</a>
```
Nog parlisweb links bevat met een identifier die (neem ik aan) niet in de API te gebruiken is, misschien kan deze data wel worden gelinkt of is die dat al?

**Comment by DanielVanHilten** [comment]
Dit zijn interne links vanuit het bronsysteem, deze zijn niet beschikbaar voor de buitenwereld. Wij kunnen deze links er misschien beter uit gaan filteren in de toekomst. Daarnaast is het id (guid) dat wordt genoemd niet een guid die aangeboden wordt via de API's. Vanuit Zaak zijn er links te maken naar andere entiteiten, een overzicht hiervan vind je op: https://opendata.tweedekamer.nl/documentatie/informatiemodel-20

**Comment by TK-Erik** [comment]
Goede vraag en we hebben de achtergrond hiervan toegelicht. Dit zal op korte termijn **niet** door ons gewijzigd worden.
