### ISSUE TITLE
Betekenis 'DatumSoort'

### ISSUE THREAD

**Issue by bartromgens** [TweedeKamerDerStaten-Generaal/OpenDataAPI2.0#40]
Wat is de betekenis van de `DatumSoort` attribute?

Ik denk dat ik dit wel kan achterhalen door wat items langs te gaan. Graag bevestiging, en mogelijk kan de documentatie dit beter uitleggen (op welk attribute heeft dit betrekking, en hoe?). Dit is verder geen issue en heeft lage prioriteit. 

**Activiteit documentatie voorbeeld:**

DatumSoort | nvarchar | 0 | 1 | Mogelijke waarden: Dag, Meerdaags, Nog geen datum bekend, Weeknummer
-- | -- | -- | -- | --

- https://opendata.tweedekamer.nl/documentatie/Activiteit

**Activiteit voorbeeld met `DatumSoort=Weeknummer`:**
https://gegevensmagazijn.tweedekamer.nl/OData/v4/2.0/Activiteit(bce89ca5-5ad3-458e-9079-a2cd5efc5beb)

Betekent dit dat de `Datum` voor deze activiteit (`2019-11-04T00:00:00+01:00`) betekent dat het gepland staat voor de week die begint op deze datum?

**Comment by DanielVanHilten** [comment]
Uit mijn hoofd: 
In de geplande activiteiten is er niet altijd bekend op welke dag het plaatsvindt. Dan wordt er eerst in de week gepland via Weeknummer. Het weeknummer van de Datum dien je in dit geval te hanteren en niet de Datum zelf.
Op jouw laatste vraag dus: Ja!

Daarnaast is het mogelijk dat een activiteit op meerdere dagen voorkomt. Wij hopen dit soort vragen in de toekomst beter te kunnen gaan duiden door per veld dit uit te gaan werken.

**Comment by bartromgens** [comment]
Dank voor de bevestiging. Wat mij betreft kan dit issue dicht als dit wordt meegenomen in algemene verbetering van documentatie. Dit heeft voor mij geen hoge prioriteit. Ik wil vooral aangeven dat er vraag is naar verbetering in documentatie (die overigens al heel veel beter is geworden).
