### ISSUE TITLE
OData Document bestand (Resource) url is lastig te vinden

### ISSUE THREAD

**Issue by bartromgens** [TweedeKamerDerStaten-Generaal/OpenDataAPI2.0#41]
Mogelijk zie ik iets over het hoofd, maar het lijkt niet eenvoudig om een url naar het daadwerkelijke bestand (PDF, ect) te vinden van een OData `Document`. 

- Ik kan in de documentatie niet vinden hoe ik een `Document` bestand kan downloaden
- Een standaard `Document` bevat geen link naar een bestand

De link naar het bestand is te vinden in het `#TK.DA.GGM.OData.Resource` attribute, maar deze is in de normale response van een `Document` niet aanwezig.

Voorbeeld:
https://gegevensmagazijn.tweedekamer.nl/OData/v4/2.0/Document(191c8c24-dc5f-46de-8d7b-475a0017a064)

Op deze manier wel (zie `#TK.DA.GGM.OData.Resource`):
https://gegevensmagazijn.tweedekamer.nl/OData/v4/2.0/Document(191c8c24-dc5f-46de-8d7b-475a0017a064)?$format=application/json;odata.metadata=full

Mogelijk is dit een OData standaard, en dus heel triviaal voor OData gebruikers. De meeste gebruikers zullen niet bekend zijn met OData. Dit is waarschijnlijk iets om te verbeteren in documentatie of standaard response.

**Comment by DanielVanHilten** [comment]
In de documentatie staat hier het volgende over bij de voorbeelden:
**Document download |** 
/Document?$format=application/json;odata.metadata=full&$filter=DocumentNummer eq '2009D35955'
Via /Resource is het document te downloaden./Document(<<guid invoeren>>)/TK.DA.GGM.OData.Resource()" of in het kort: /Document(<<guid invoeren>>)/Resource

In jouw geval zou je dus dit kunnen doen:
https://gegevensmagazijn.tweedekamer.nl/OData/v4/2.0/Document(191c8c24-dc5f-46de-8d7b-475a0017a064)/Resource

Kun je hiermee verder?

**Comment by bartromgens** [comment]
Ah, dank! Dan heb ik dus iets over het hoofd gezien. `/Resource` :+1: 

Ik kan hier zeker mee verder.

Het was vooral een waarneming dat het waarschijnlijk voor een nieuwe gebruiker niet eenvoudig te vinden is. Als het ergens gedocumenteerd is, lijkt me dat voorlopig voldoende.
