### ISSUE TITLE
Lagere resolutie foto's via API dan via TK website

### ISSUE THREAD

**Issue by bwbroersma** [TweedeKamerDerStaten-Generaal/OpenDataAPI2.0#42]
## Website
![Foto Dennis Wiersma (VVD)](https://www.tweedekamer.nl/sites/default/files/styles/member_parliament_header/public/atoms/images/vvd_wiersma.jpg?itok=LslCZ68X)
```url
https://www.tweedekamer.nl/sites/default/files/styles/member_parliament_header/public/atoms/images/vvd_wiersma.jpg?itok=LslCZ68X
```
via [Tweede Kamer website](https://www.tweedekamer.nl/kamerleden_en_commissies/alle_kamerleden/wiersma-ad-vvd)

<hr>

## API

![Foto Dennis Wiersma (VVD)](https://user-images.githubusercontent.com/4252918/66132978-337c2400-e5f6-11e9-8c63-32e378d2e2c4.jpg)
```url
https://gegevensmagazijn.tweedekamer.nl/OData/v4/2.0/Persoon(c3b1dca8-2cb4-4025-9527-36163a098c1f)/TK.DA.GGM.OData.Resource()
```
via [Tweede Kamer API](https://gegevensmagazijn.tweedekamer.nl/OData/v4/2.0/Persoon(c3b1dca8-2cb4-4025-9527-36163a098c1f)?$format=application/json;odata.metadata=full)

**Comment by DanielVanHilten** [comment]
De foto's die gebruikt worden in het overzicht van de Tweede Kamerleden staan in de API:
https://www.tweedekamer.nl/kamerleden_en_commissies/alle_kamerleden?last_name=w
De redactie van TweedeKamer.nl voegt zelf nog een grotere (resolutie) foto toe op de bio-pagina, deze is inderdaad niet verkrijgbaar via de API. Op andere sites wordt wel dezelfde foto als in de API gebruikt, bijvoorbeeld:
https://www.houseofrepresentatives.nl/members_of_parliament/members_of_parliament/wiersma-ad-vvd

Geeft dit antwoord op je vraag?

**Comment by bwbroersma** [comment]
Ok
