### ISSUE TITLE
PersoonNevenfunctie IsActief betekenis / documentatie

### ISSUE THREAD

**Issue by bwbroersma** [TweedeKamerDerStaten-Generaal/OpenDataAPI2.0#43]
Wat is de betekenis van `IsActief` bij `PersoonNevenfunctie`?
De [documentatie](https://opendata.tweedekamer.nl/documentatie/PersoonNevenfunctie) zegt er niets over. Het wordt me ook niet duidelijk als ik [$filter = IsActief eq false](https://gegevensmagazijn.tweedekamer.nl/OData/v4/2.0/PersoonNevenfunctie?$filter=IsActief%20eq%20false) bekijk.

**Comment by TK-Erik** [comment]
Is inmiddels verholpen en [documentatie](https://opendata.tweedekamer.nl/documentatie/PersoonNevenfunctie) is aangepast.
