### ISSUE TITLE
FractieZetelVacature.Functie documentatie niet volledig (Fractievoorzitter ontbreekt)

### ISSUE THREAD

**Issue by bartromgens** [TweedeKamerDerStaten-Generaal/OpenDataAPI2.0#44]
De documentatie van FractieZetelVacature.Functie lijkt niet volledig. 

`FractieZetelVacature.Functie` heeft volgens de documentatie de mogelijke waarde(n) : `Lid`
bron: https://opendata.tweedekamer.nl/documentatie/FractieZetelVacature

In de huidige data kom ik ook de waarde `Fractievoorzitter` tegen. 

Voorbeeld: https://gegevensmagazijn.tweedekamer.nl/OData/v4/2.0/FractieZetelVacature(148e6358-c46e-4b64-8c2a-9ae99c60df49)

Waarschijnlijk moet de documentatie hier bijgewerkt worden?

**Comment by JPBenard** [comment]
Beste Bart, je hebt helemaal gelijk! In het bronsysteem is deze waarde kortgeleden voor het eerst gebruikt: zoals je kunt zien is er even een vacature voor fractievoorzitter bij de PvdD geweest.
We hebben het aangepast in de documentatie.
Dank voor het melden.
Hartelijke groet,
Jan-Paul Benard
contentspecialist ODP
