### ISSUE TITLE
FractieAanvullendGegeven heeft geen resultaten

### ISSUE THREAD

**Issue by bartromgens** [TweedeKamerDerStaten-Generaal/OpenDataAPI2.0#45]
Er lijken geen items van `FractieAanvullendGegeven` te bestaan.

Voorbeeld overzicht:
https://gegevensmagazijn.tweedekamer.nl/OData/v4/2.0/FractieAanvullendGegeven?$orderby=GewijzigdOp+desc&$filter=Verwijderd+eq+false&$format=application/json;odata.metadata=full&$top=10

Klopt dit?

**Comment by JPBenard** [comment]
Dit klopt inderdaad met de database!

**Comment by bartromgens** [comment]
Duidelijk. Dan kan dit dicht.
