### ISSUE TITLE
Afbeelding informatiemodel 2.0 verdwenen

### ISSUE THREAD

**Issue by JPBenard** [TweedeKamerDerStaten-Generaal/OpenDataAPI2.0#47]
Op dit moment zijn de afbeeldingen op https://opendata.tweedekamer.nl/documentatie/informatiemodel-20 verdwenen. We werken eraan een verbeterde versie terug te plaatsen!

**Comment by JPBenard** [comment]
Inmiddels is de afbeelding weer zichtbaar. We werken nog steeds aan het plaatsen van die verbeterde versie.

**Comment by bartromgens** [comment]
@JPBenard Het ontbreken was me opgevallen. Dat geeft aan hoe belangrijk deze diagrammen zijn. Mooi dat ze er weer zijn. 
Voor mij zijn ze, samen met de Entiteit beschrijvingen (attributen en relaties), het meest gebruikte deel van de documentatie. 

Ik kijk uit naar een verbeterde versie!

**Comment by JPBenard** [comment]
De meest recente versie van het informatiemodel staat op https://opendata.tweedekamer.nl/documentatie/informatiemodel-20 !
