### ISSUE TITLE
Wat is een "bijzondere gedelegeerde" functie bij een zaakactor?

### ISSUE THREAD

**Issue by Jonakemon** [TweedeKamerDerStaten-Generaal/OpenDataAPI2.0#53]
Bijvoorbeeld bij de query  http://37.97.129.67/OData/v4/2.0/Zaak(5b2d075f-153f-4de5-860d-29e88f4c07ea)?$expand=ZaakActor($expand=Fractie) zie ik G.M.Mc. William als bijzonder gedelegeerde staan. Hij hoort niet bij een fractie.

Ik vroeg me af wat zijn rechten zijn als bijzonder gedelegeerde. Of is het een 'ceremoniele' steun voor de motie en voor de rest niets?

**Comment by JPBenard** [comment]
Hi,

Een bijzondere gedelegeerde is een lid van de Staten van Aruba, Curaçao of Sint Maarten die als afgevaardigde aanwezig is bij een debat in de Eerste en/of Tweede Kamer of de Verenigde Vergadering als daar een ontwerp-rijkswet wordt behandeld.
Een bijzondere gedelegeerde heeft geen stemrecht, maar mag wel het woord voeren, moties indienen en heeft in de Tweede Kamer het recht van amendement.

zie voor meer informatie: https://www.parlement.com/id/vk4red82myt6/bijzondere_gedelegeerde

**Comment by Jonakemon** [comment]
Merci!

**Comment by Jonakemon** [comment]
Merci!
