### ISSUE TITLE
Hoe snel wordt kabinetsappreciate opgenomen in de API?

### ISSUE THREAD

**Issue by Jonakemon** [TweedeKamerDerStaten-Generaal/OpenDataAPI2.0#55]
Kabinetsappreciate is een van de belangrijkste factors voor het bepalen of een motie wel of niet wordt aangenomen. Tijdens het debat wordt die appreciatie door een bewindspersoon vrijwel direct gegeven. Het viel me op dat in de API die informatie pas later bekend wordt. Ik vroeg me af hoe snel de appreciatie in de API wordt opgenomen, en of er iets in het werkproces veranderd kan worden om die informatie sneller te kunnen ontsluiten.

Bijvoorbeeld bij de APB gisteren is de appreciatie direct gegeven [in het debat](https://www.tweedekamer.nl/kamerstukken/plenaire_verslagen/detail/ed105caf-b05a-4c07-8a13-6bc3e3192bfd), maar is nog niet beschikbaar in de [API](http://37.97.129.67/OData/v4/2.0/Zaak?$expand=Agendapunt&$filter=GestartOp%20gt%202020-09-16T00:00:00Z%20and%20Soort%20eq%20%27Motie%27).

**Comment by JPBenard** [comment]
Hi, excuus voor de late reactie.
De kabinetsappreciatie wordt inderdaad direct in het debat gegeven door een bewindspersoon, en is in die zin dus snel beschikbaar in het Verslag. De kabinetsappreciatie per motie/amendement aangeven is onderdeel van het werkproces van de Griffie van de Tweede Kamer. Zodra de kabinetsappreciatie wordt toegevoegd in het bronsysteem van de Griffie is het nagenoeg onmiddellijk (neartime) beschikbaar in de API. Dat gebeurt uiteraard z.s.m., maar ik zal eens navragen of daar een termijn voor is.

**Comment by JPBenard** [comment]
Update: navraag bij de Griffie leert dat de kabinetsappreciaties bij moties en amendementen de dag na het debat worden verwerkt en onder normale omstandigheden binnen een dag (= 24 uur) beschikbaar zijn.

**Comment by Jonakemon** [comment]
Super, thanks!
