### ISSUE TITLE
Missende relatiekoppeling bij de tabel Zaak

### ISSUE THREAD

**Issue by henkdvries** [TweedeKamerDerStaten-Generaal/OpenDataAPI2.0#56]
In het informatie model wordt aangegeven dat de tabel Zaak gekoppeld is aan meerdere tabellen (Activitieit, Agendapunt, Besluit, Document en Kamerstuk Dossier). Enige tabel met een gedefinieerde relatie naar Zaak is Zaakactor.

Nu vroeg ik mij af of deze tabellen op een andere manier met elkaar verbonden zijn want dat is nu niet duidelijk. 

![De tabellen in kwestie](https://user-images.githubusercontent.com/45108194/99371683-84fd7600-28bf-11eb-8a52-d05c65ef8f0c.png)

**Comment by JPBenard** [comment]
Hoi,
ik weet niet helemaal zeker of ik begrijp wat je bedoelt.. Als je kijkt op https://gegevensmagazijn.tweedekamer.nl/OData/v4/2.0/$metadata dan kun je zien dat Zaak gekoppeld is aan de volgende entiteiten:
<NavigationProperty Name="Activiteit" Type="Collection(TK.DA.GGM.OData.Activiteit)"/>
<NavigationProperty Name="Agendapunt" Type="Collection(TK.DA.GGM.OData.Agendapunt)"/>
<NavigationProperty Name="Besluit" Type="Collection(TK.DA.GGM.OData.Besluit)"/>
<NavigationProperty Name="ZaakActor" Type="Collection(TK.DA.GGM.OData.ZaakActor)"/>
<NavigationProperty Name="Kamerstukdossier" Type="Collection(TK.DA.GGM.OData.Kamerstukdossier)"/>
<NavigationProperty Name="GerelateerdVanuit" Type="Collection(TK.DA.GGM.OData.Zaak)"/>
<NavigationProperty Name="GerelateerdNaar" Type="Collection(TK.DA.GGM.OData.Zaak)"/>
<NavigationProperty Name="VervangenVanuit" Type="Collection(TK.DA.GGM.OData.Zaak)"/>
<NavigationProperty Name="VervangenDoor" Type="Collection(TK.DA.GGM.OData.Zaak)"/>
<NavigationProperty Name="Document" Type="Collection(TK.DA.GGM.OData.Document)"/>

Aan de hand daarvan kun je er andere tabellen bij expanden, bijvoorbeeld:

https://gegevensmagazijn.tweedekamer.nl/OData/v4/2.0/Zaak?&$filter=Nummer%20eq%20%272020Z11731%27&$expand=Besluit($expand=Stemming)
of: 

https://gegevensmagazijn.tweedekamer.nl/OData/v4/2.0/Zaak?&$filter=Nummer%20eq%20%272020Z11731%27&$expand=Agendapunt($expand=Activiteit)

Is dat wat je zoekt?

**Comment by henkdvries** [comment]
Aah, dat verklaard het. 

Ik had wel graag gezien dat dat er eenheid is omtrent relaties tussen tabellen. Elke andere tabel heeft wel de juiste foreign keys om relaties aan te geven alleen Zaak dan weer niet.

Wat jammer is dat ik nu dus 80 duizend entries in mijn database heb staan die waardeloos zijn omdat ik daar geen relatie kan leggen tussen de tabellen op een andere manier.
