### ISSUE TITLE
Markeer issues die niet gefixt/geïmplementeerd worden met `wontfix` label

### ISSUE THREAD

**Issue by ndkv** [TweedeKamerDerStaten-Generaal/OpenDataAPI2.0#6]
Complimenten voor het opzetten van deze issue tracker! 

Heel fijn dat jullie ook de issues/enhancements gaan bijhouden die niet geïmplementeerd zullen worden. 

Een voorstel voor een kleine verbetering van het proces: markeer deze issues met een/de `wontfix` label zodat je niet telkens de laatste zin van een issue moet lezen om te achterhalen of iets wel/niet gefixt wordt. 😇

**Comment by DanielVanHilten** [comment]
Bedankt voor je feedback, ik heb het net gelabeld.
