### ISSUE TITLE
Document titel en onderwerp bevatten soms trailing whitespaces

### ISSUE THREAD

**Issue by bartromgens** [TweedeKamerDerStaten-Generaal/OpenDataAPI2.0#7]
Dit is ter kennisgeving en geen probleem. Ik denk dat het wel een bewuste keuze moet zijn. 

Sommige `Document` titels en onderwerpen bevatten trailing whitespaces in OData V4.

Voorbeeld: https://gegevensmagazijn-a.tweedekamer.nl/OData/v4/1.0/Document(b2c6c477-e90b-4570-9b9f-11b95615208a)

Ik vind het prima als dit bewust zo is omdat het zo uit de 'bron' komt en die niet wordt aangepast.
Kwam het tegen omdat een unittest faalde. In de oude versie was deze whitespace er dus niet.

**Comment by DanielVanHilten** [comment]
Heel gaaf dat het uit jouw unittests komt. Voorheen is deze trailing whitespace inderdaad verwijderd. Nu kiezen we ervoor alles 1:1 te houden. In het bronsysteem staan deze spaties inderdaad ook.

Bedankt voor je heldere melding!
