### ISSUE TITLE
The Any/All nesting limit of '1' has been exceeded

### ISSUE THREAD

**Issue by bartromgens** [TweedeKamerDerStaten-Generaal/OpenDataAPI2.0#8]
Op dit moment zit er een filter 'nesting limit' van 1 op de OData V4 acceptatie. 

Is dit bewust veranderd, en zal dit ook zo blijven?

Als ik bijvoorbeeld alle Besluiten gerelateerd aan een Kamerdossier wil vinden in 1 query, heb ik volgens mij nesting nodig. Het kan natuurlijk ook in meerdere requests, maar het is wel goed om te weten wat er uiteindelijk toegestaan zal worden.

Voobeeld: https://gegevensmagazijn-a.tweedekamer.nl/OData/v4/1.0/Besluit?$filter=Zaak/any(z:z/Kamerstukdossier/any(d:d/Nummer+eq+33885))&$format=application/json;odata.metadata=full

**Comment by DanielVanHilten** [comment]
Dit is inderdaad een standaard instelling MaxAnyAllExpressionDepth die in de V4 zo staat. We kunnen dit aanpassen naar 2 of 3. We weten alleen niet zeker wat voor performance dit kost. Gaat jou dit een hoop code schelen als dit naar 2 of 3 gaat?

**Comment by bartromgens** [comment]
Voor mij is het geen probleem. Ik maakte er niet veel gebruik van en kan het makkelijk herschrijven.
Het wordt iets lastiger om generieke queries te maken/combineren, maar het houdt het ook weer simpel.

Ik heb liever meer requests dan zware queries, als er ergens een limiet op komt.
Het is zo dus prima.

**Comment by DanielVanHilten** [comment]
Goed punt. We gaan nog performance tests doen en we zijn bezig met een onderzoek om nog meer op te kunnen schalen bij veel verzoeken. Ook jullie feedback is daarin van belang uiteraard.
