### ISSUE TITLE
Entiteit Reservering mist ActiviteitNummer

### ISSUE THREAD

**Issue by DanielVanHilten** [TweedeKamerDerStaten-Generaal/OpenDataAPI2.0#9]
De link naar Activiteit is wel te maken maar er is tevens een veld in het bronsysteem "ActiviteitNummer" die nog niet is gemapt. Komt mee in volgende release.

**Comment by bartromgens** [comment]
@DanielVanHilten Dank voor het melden. Dit soort minor issues inzichtelijk hebben is echt heel handig. Ik ga voortaan issues niet vervuilden met dankwoorden ;) Maar wil eenmalig toch even laten weten dat het gezien en gewaardeerd wordt.

**Comment by DanielVanHilten** [comment]
Dit is meegekomen in de "Acceptatie release 2", het nummer is nu beschikbaar.
